language: smalltalk
sudo: false

install:
  - pip install --user benchupload

os:
  - linux
#  - osx
services: 
  - mongodb
 
addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server
 
smalltalk:
  - Pharo-5.0
  - Pharo-4.0
  - Pharo-3.0

before_script:
  - mongo test --eval 'db.createUser(\{ user: "pharounittest", pwd: "test", roles: [] \});'

# bob-bench xUnit file analysis
after_success:
  - benchupload --dir=$SMALLTALK_CI_BUILD
after_failure:
  - benchupload --dir=$SMALLTALK_CI_BUILD
